import type { Metadata } from 'next';
import { Roboto, Lora } from 'next/font/google';

import './globals.css';
import Menu from '@/components/Menu/Menu';
import Providers from '@/lib/Providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import MusicWrapper from '@/components/Music/MusicWrapper';
import DesktopAudioWrapper from '@/components/Music/DesktopAudioWrapper';
export const loraFont = Lora({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-lora',
});

export const robotoFont = Roboto({
    subsets: ['latin'],
    weight: ['400', '700'],
    variable: '--font-roboto',
});
export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang='en'
            className={`${loraFont.variable} ${robotoFont.variable}`}>
            <body>

                <Providers>
                    {children}
                    <ToastContainer />
                    {/* <MusicWrapper /> */}
                    <DesktopAudioWrapper />
                </Providers>
            </body>
        </html>
    );
}
